### ISSUE TITLE
can not find okok in hacs

### ISSUE THREAD

**Issue by lbh3344** [rrooggiieerr/homeassistant-okokscale#2]
Sorry, I can not find okok in hacs. Thanks

![image](https://github.com/rrooggiieerr/homeassistant-okokscale/assets/140432396/3492e9a6-83b7-4445-88fb-bcf65b67c4aa)

**Comment by lbh3344** [comment]
I mannuly installed it but when I clicked it, shown no device

![image](https://github.com/rrooggiieerr/homeassistant-okokscale/assets/140432396/3c92a07b-f127-435e-813b-09702b8644a7)

**Comment by hiagocosta** [comment]
is not showing on me too,

should we change some config of the bluetooth in the HASSOS?

**Comment by rrooggiieerr** [comment]
It could very well be that your scale uses a different protocol. I only own one scale and this integration works for me. You need to do more research yourself because with the information provided I can't be of any help

**Comment by hiagocosta** [comment]
Is there any way to reverse this engineering on that protocol?

Em sex., 12 de abr. de 2024 às 00:00, rrooggiieerr ***@***.***>
escreveu:

**Comment by rrooggiieerr** [comment]
Yes, if you're an Android user you can try the app BLE Scanner which shows you lots of details about your Bluetooth device. 
Then you have to figure out which service changes when you're using the scale.

You can also try if your scale works with this app: https://github.com/oliexdev/openScale
