### ISSUE TITLE
Sensor gives a non numeric value in template sensor

### ISSUE THREAD

**Issue by Mattdejong** [rrooggiieerr/homeassistant-okokscale#4]
The code:

sensor:
    - platform: template
        sensors: 
             scale_weight:
                 unit_of_measurement: "kg"
        value_template ”{{states('sensor.okok_scale_b2c5_weight') }}"

output:

Sensor x has device class 'weight', state class 'measurement' unit 'kg' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'sensor: - platform: template sensors: scale_weight: unit_of_measurement: "kg" value_template: "16.1"' (<class 'str'>)

The scale gives a string back instead of a float. I want to make a template sensor because the scale goes in a deepsleep and gives back the value unavailable.

**Comment by rrooggiieerr** [comment]
Hi Matt,

Sensors in HA always give string values, even if they're numeric values. To use them in templates you need to cast them back to their original type like so: `states('sensor.okok_scale_b2c5_weight') | float`

Frome the HA documentation:
states can also be used as a function, states(entity_id, rounded=False, with_unit=False), **which returns the state string** (not the state object) of the given entity, unknown if it doesn’t exist, and unavailable if the object exists but is not available.

**Comment by Mattdejong** [comment]
Even with the float it still gives: Sensor None has device class 'weight', state class 'measurement' unit 'kg' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'template: sensor: - name: "Gewicht Schaal" unit_of_measurement: "kg" state: 77.6' (<class 'str'>).

**Comment by rrooggiieerr** [comment]
I think the error actually applies to your own template sensor, and not to the scale sensor.

You also to use the legacy template sensor format
https://www.home-assistant.io/integrations/template/

Your value_template is missing the `:` and the value is between two kind of brackets `”` and `"`.

The modern format should be something like:
```
template:
  - sensor:     
    - name: ...
      unique_id: ...
      unit_of_measurement: "kg"
      state: "{{ states('sensor.okok_scale_b2c5_weight') | float }}"
```

You can also try out your template in the Developer Tools > Template

**Comment by Mattdejong** [comment]
Hmmmm, Looks interesting I will take a look into it. I want also want to Multiply the state of the scale, but it has more to do with the protein intake for m2. You sure are a help 2 me. im really still a beginner. I don't know everything, and the frustrating part is that: every solution that is on the internet says it works with this methode, even chatgpt. But I can't get it to work. I will open a home assistant question if its not a bug, thanks for the response
