### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by freijn** [rrooggiieerr/homeassistant-okokscale#8]
Hi Rogier,

My scale is not reporting in HA anymore.  Any idea what is going on?
Are/should there be any logfiles?

Core 2024.9.3
Supervisor 2024.9.1
o.s. 13.1
Okokscale 0.03

Many thanks for your time!

    Frank

**Comment by mikje** [comment]
here neither

Core 2024.10.1
Supervisor 2024.09.1
Operating System 13.1
Okokscale 0.03

**Comment by rrooggiieerr** [comment]
Sorry, but for me it's working with the lates HA. Maybe you could enable debug logging and see what's being logged

**Comment by freijn** [comment]
With the latest software its working again indeed.   

Many thanks for your support!
